# Generated by Django 5.0.6 on 2024-07-08 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoProyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minicoreapp.empleado')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minicoreapp.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='proyectos',
            field=models.ManyToManyField(through='minicoreapp.EmpleadoProyecto', to='minicoreapp.proyecto'),
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_empezar', models.DateField()),
                ('trabajo_estimado', models.IntegerField()),
                ('estado', models.CharField(choices=[('In progress', 'In progress'), ('Done', 'Done')], max_length=20)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minicoreapp.empleado')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minicoreapp.proyecto')),
            ],
        ),
    ]
