# Generated by Django 5.0.6 on 2024-07-08 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minicoreapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='proyectos',
        ),
        migrations.DeleteModel(
            name='EmpleadoProyecto',
        ),
    ]
