# Generated by Django 5.0.6 on 2024-07-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minicoreapp', '0002_remove_empleado_proyectos_delete_empleadoproyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='proyectos',
            field=models.ManyToManyField(to='minicoreapp.proyecto'),
        ),
    ]
